env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/warnings

parserOptions:
  ecmaVersion: 9
  sourceType: module

globals:
  html: readonly

rules:
  semi: error
  no-shadow: error
  no-unused-vars:
    - error
