sudo: true
language: node_js
node_js:
  - "13"
cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable # have Travis install Chrome stable.
  sauce_connect: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - COVERAGE=true yarn test --single-run --console --stack --log-level debug

after_success:
  - yarn run coverage

git:
  submodules: false
