sudo: true

language: node_js

node_js:
  - "10"

addons:
  chrome: stable # have Travis install Chrome stable.

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn test --single-run

after_success:
  - yarn run coverage

git:
  submodules: false
