[build]
  base    = ""
  publish = "site/public"
  command = "yarn build && (cd site && hugo --gc --minify)"

[context.production]
  [context.production.environment]
    YARN_VERSION = "1.12.3"
    HUGO_VERSION = "0.53"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
