[build]
  base    = ""
  publish = "fixtures/lit-html"
  command = "yarn build"

[context.production]
  [context.production.environment]
    YARN_VERSION = "1.12.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
